language: python
matrix:
  include:
  - python: '2.6'
    env:                             CATEGORY="nightly"  EXTRAS="yes"
  #- python: '2.7'
  #  env:                             CATEGORY="nightly"  EXTRAS="yes"
  #- python: '3.4'
  #  env:                             CATEGORY="nightly"  EXTRAS="yes"
  #- python: '3.5'
  #  env:                             CATEGORY="nightly"  EXTRAS="yes"
install:
- sudo apt-get update
# We do this conditionally because it saves us some downloading if the
# version is the same.
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
     wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  else
     wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda create -n test python=${TRAVIS_PYTHON_VERSION}
- if [ -n "${EXTRAS}" ]; then conda install -y --channel conda-forge pyomo.extras; fi
- if [ "${TRAVIS_PYTHON_VERSION}" = "2.6" ]; then pip install ordereddict; fi
- conda install -y --channel conda-forge glpk
- conda install -y --channel cachemeorg ipopt_bin
- pip install coverage
- pip install git+https://github.com/PyUtilib/pyutilib
- pip install git+https://github.com/Pyomo/pyomo
- which python
- python --version
- python setup.py develop -N
- cat pyomo.aux.simplemodel.egg-info/SOURCES.txt
script:
- which nosetests
- nosetests --verbosity=3 -x .
