language: python
matrix:
  include:
  - python: '2.7'
    env:                             CATEGORY="nightly"  EXTRAS="yes"
  - python: '3.4'
    env:                             CATEGORY="nightly"  EXTRAS="yes"
  - python: '3.5'
    env:                             CATEGORY="nightly"  EXTRAS="yes"
install:
- sudo apt-get update
#
# Setup miniconda and activate the testenv environment
#
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
     wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  else
     wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda create -f -y -n testenv python=${TRAVIS_PYTHON_VERSION}
- source activate testenv
#
# Install supporting packages
#
- if [ -n "${EXTRAS}" ]; then conda install -y --channel conda-forge pyomo.extras; fi
- if [ "${TRAVIS_PYTHON_VERSION}" = "2.6" ]; then pip install ordereddict; fi
- conda install -y --channel conda-forge glpk
- conda install -y --channel cachemeorg ipopt_bin
- pip install coverage
#
# Install PyUtilib and Pyomo (master branches)
#
- pip install git+https://github.com/PyUtilib/pyutilib
- pip install git+https://github.com/Pyomo/pyomo
#
# Install this package
#
- which python
- python --version
- python setup.py install
script:
- nosetests --verbosity=3 -x .
