environment:

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.


    - PYTHON_VERSION: 2.7
      #PYTHON: "C:\\Python27"
      PYTHON: "C:\\Miniconda-x64"
      CATEGORY: "nightly"

    - PYTHON_VERSION: 3.5
      #PYTHON: "C:\\Python35"
      PYTHON: "C:\\Miniconda35-x64"
      CATEGORY: "nightly"

    - PYTHON_VERSION: 3.6
      #PYTHON: "C:\\Python36"
      PYTHON: "C:\\Miniconda36-x64"
      CATEGORY: "nightly"

    - PYTHON_VERSION: 3.7
      #PYTHON: "C:\\Python37"
      PYTHON: "C:\\Miniconda37-x64"
      CATEGORY: "nightly"

install:
  # We need wheel installed to build wheels
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\Library\\bin;%PATH%"
  - python --version
  #
  # Set standardized ways to invoke conda for the various channels.  We
  # are seeing strange issues where conda-forge and cachemeorg are
  # fighting with anaconda over the version of core packages (notably,
  # conda).  The following prevents conda-forge and cacheme.org from
  # overriding anaconda.
  #
  - SET CONDA_INSTALL=conda install -q -y
  - "SET ANACONDA=%CONDA_INSTALL% -c anaconda"
  - "SET CONDAFORGE=%CONDA_INSTALL% -c conda-forge --no-update-dependencies"
  - "SET CACHEMEORG=%CONDA_INSTALL% -c cachemeorg --no-update-dependencies"
  #
  # Update conda, then force it to NOT update itself again
  #
  - conda config --set always_yes yes
  - conda update -q -y -c anaconda conda
  - conda config --set auto_update_conda false
  #
  - "%CONDAFORGE% setuptools pip"
  - "IF %PYTHON_VERSION%==2.6 (python -m pip install ordereddict)"
  - python -m pip install coverage
  - python -m pip install codecov
  #
  - "%CONDAFORGE% glpk"
  - "glpsol -v"
  # NOTE: conda-forge doesn't build ipopt for Windows....
  - "%CACHEMEORG% ipopt_bin"
  - "ipopt -v"
  #
  - "python -m pip install nose"
  - "python -m pip install git+https://github.com/PyUtilib/pyutilib"
  - "python -m pip install git+https://github.com/Pyomo/pyomo"
  - "python setup.py develop"

build: off

test_script:
  # Put your test command here.
  # If you don't need to build C extensions on 64-bit Python 3.3 or 3.4,
  # you can remove "build.cmd" from the front of the command, as it's
  # only needed to support those cases.
  # Note that you must use the environment variable %PYTHON% to refer to
  # the interpreter you're using - Appveyor does not do anything special
  # to put the Python evrsion you want to use on PATH.
  - "nosetests -v"

#after_test:
  # This step builds your wheels.
  # Again, you only need build.cmd if you're building C extensions for
  # 64-bit Python 3.3/3.4. And you need to use %PYTHON% to get the correct
  # interpreter
  #- "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"

#artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  #- path: dist\*

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
  #- pip install codecov
  #- cp ../.coverage .
  #- codecov
