name: pyomo-checks/conda

on:
  push:
    branches:
      - master

jobs:
  pyomo-linux-tests:
    name: py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - name: Setup Conda
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Conda info
      shell: bash -l {0}
      run: |
        conda info
        conda init bash
        conda env list
    - name: Conda list
      shell: pwsh
      run: conda list
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda env list
        conda activate test
        python -m pip install --upgrade pip
        conda install -c conda-forge pyutilib
        conda install -c conda-forge pyomo
        python setup.py develop
        pip install nose
        pip install pyyaml
        conda install -c conda-forge glpk ipopt
    - name: Run tests
      shell: bash -l {0}
      run: |
        nosetests -v .
